name: CI/CD to EC2

on:
  push:
    branches: ["test"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t kevinseya/logistic_payment_verification:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push kevinseya/logistic_payment_verification:latest

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            # Verificar e instalar Docker si es necesario en Ubuntu
            if ! command -v docker &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Descargar la imagen
            sudo docker pull kevinseya/logistic_payment_verification:latest

            # Detener y eliminar el contenedor anterior
            sudo docker stop logistic_payment_verification || true
            sudo docker rm logistic_payment_verification || true

            # Generar el archivo .env con variables secretas
            echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
            echo "NOTIFICATION_WEBHOOK_PAYMENT_URL=${{ secrets.NOTIFICATION_WEBHOOK_PAYMENT_URL }}" >> .env

            # Ejecutar el nuevo contenedor
            sudo docker run -d --name logistic_payment_verification \
              --env-file .env \
              -p 8088:8088 \
              kevinseya/logistic_payment_verification:latest
          EOF
